[package]
name = "brew-maintainer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", default-features = false, features = ["now", "pure-rust-locales", "std", "clock"] }

[profile.release]
debug = false
strip = "symbols"
opt-level = "z"
lto = true
panic = "abort"
